### ISSUE TITLE
Todo list of site features

### ISSUE THREAD

**Issue by AlexMooney** [AlexMooney/AlexMooney.github.io#2]
- [x] add real index page and about
- [ ] add an RSS feed
- [ ] add categories pages. [see here](https://blog.webjeda.com/jekyll-categories/)
